package com.leadproject.service;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import com.leadproject.dto.LeadImportResponse;
import com.leadproject.dto.PhoneCallPlan;
import com.leadproject.model.Lead;
import com.leadproject.repository.LeadRepository;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

@Service
public class LeadImportService {

    private static final Logger logger = LoggerFactory.getLogger(LeadImportService.class);

    private final LeadRepository leadRepository;

    public LeadImportService(LeadRepository leadRepository) {
        this.leadRepository = leadRepository;
    }

    @Transactional
    public LeadImportResponse importFromExcel(MultipartFile file) {
        logger.info("Starting lead import: fileName={}, size={}",
            file == null ? null : file.getOriginalFilename(), file == null ? 0 : file.getSize());
        if (file == null || file.isEmpty()) {
            throw new IllegalArgumentException("Excel file is required");
        }

        String originalName = file.getOriginalFilename() == null ? "" : file.getOriginalFilename().toLowerCase();
        String contentType = file.getContentType() == null ? "" : file.getContentType().toLowerCase();
        if (!originalName.endsWith(".xlsx") && !contentType.contains("spreadsheetml") && !contentType.contains("excel")) {
            throw new IllegalArgumentException("Please upload a valid .xlsx Excel file");
        }

        try (InputStream inputStream = file.getInputStream()) {
            byte[] header = inputStream.readNBytes(4);
            if (header.length < 4 || header[0] != 0x50 || header[1] != 0x4B || header[2] != 0x03 || header[3] != 0x04) {
                throw new IllegalArgumentException("Uploaded file is not a valid Excel (.xlsx) file. Please use a real Excel workbook generated by Excel/LibreOffice.");
            }
        } catch (IllegalArgumentException e) {
            throw e;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to read Excel file: " + e.getMessage(), e);
        }

        List<String> errors = new ArrayList<>();
        int imported = 0;
        int skipped = 0;

        try (InputStream inputStream = file.getInputStream(); Workbook workbook = new XSSFWorkbook(inputStream)) {
            Sheet sheet = workbook.getSheetAt(0);
            for (int rowIndex = 1; rowIndex <= sheet.getLastRowNum(); rowIndex++) {
                Row row = sheet.getRow(rowIndex);
                if (row == null) {
                    continue;
                }

                String name = getCellValue(row, 0);
                String phone = getCellValue(row, 1);
                String email = getCellValue(row, 2);
                String source = getCellValue(row, 3);

                if (name == null || name.isBlank() || phone == null || phone.isBlank()) {
                    skipped++;
                    continue;
                }

                String normalizedPhone = normalizePhone(phone);
                if (leadRepository.existsByPhone(normalizedPhone)) {
                    skipped++;
                    continue;
                }

                Lead lead = new Lead();
                lead.setName(name.trim());
                lead.setPhone(normalizedPhone);
                lead.setEmail(email != null ? email.trim() : null);
                lead.setIndustry("REAL_ESTATE");
                lead.setSource(source != null && !source.isBlank() ? source.trim() : "EXCEL_UPLOAD");
                lead.setStatus("NEW");
                lead.setConsentStatus(Lead.ConsentStatus.VALID);
                lead.setScore(0);
                lead.setScoreBand("COLD");
                lead.setSummary("Awaiting qualification call");
                lead.setUpdatedAt(java.time.LocalDateTime.now());

                leadRepository.save(lead);
                imported++;
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to import Excel file: " + e.getMessage(), e);
        }

        LeadImportResponse response = LeadImportResponse.builder()
                .imported(imported)
                .skipped(skipped)
                .errors(errors)
                .build();
        logger.info("Lead import completed: imported={}, skipped={}, errors={}",
            imported, skipped, errors.size());
        return response;
    }

    public List<String> getRealEstateQuestions() {
        logger.debug("Loading real-estate qualification questions");
        return List.of(
                "Are you looking to buy, rent, sell, or invest?",
                "Which areas and property types are you considering?",
                "What budget range are you comfortable with?",
                "When do you plan to move or purchase?",
                "Are you the decision maker?",
                "When should a property consultant contact you?"
        );
    }

    public PhoneCallPlan buildPhoneCallPlan(String phone, String leadName, String source) {
        logger.info("Building phone call plan: phone={}, leadName={}, source={}", phone, leadName, source);
        String normalizedPhone = phone == null ? "" : phone.trim();
        String safeName = leadName == null || leadName.isBlank() ? "lead" : leadName;

        return PhoneCallPlan.builder()
                .phone(normalizePhone(normalizedPhone))
                .leadName(safeName)
                .source(source == null || source.isBlank() ? "website_form" : source)
                .industry("REAL_ESTATE")
                .scriptIntro("Hello, this is a property qualification call. We are calling regarding your interest in Dubai property. May I ask a few quick questions to understand your requirement?")
                .questions(getRealEstateQuestions())
                .summaryTemplate("Lead: %s. Interested in %s property. Budget: %s. Preferred area: %s. Timeline: %s. Decision maker: %s. Preferred callback: %s.")
                .nextAction("Create an outbound property consultation callback for the salesperson after the qualification call.")
                .build();
    }

    private String getCellValue(Row row, int index) {
        if (row.getCell(index) == null) {
            return null;
        }
        return switch (row.getCell(index).getCellType()) {
            case STRING -> row.getCell(index).getStringCellValue();
            case NUMERIC -> String.valueOf((long) row.getCell(index).getNumericCellValue());
            case BOOLEAN -> String.valueOf(row.getCell(index).getBooleanCellValue());
            default -> row.getCell(index).toString();
        };
    }

    private String normalizePhone(String value) {
        String normalized = value == null ? "" : value.trim();
        if (normalized.isEmpty()) {
            return normalized;
        }
        normalized = normalized.replace(" ", "").replace("-", "").replace("(", "").replace(")", "");
        if (!normalized.startsWith("+")) {
            normalized = "+" + normalized;
        }
        return normalized;
    }
}
